print("original list")
l1=[10,20,30,40]
print(l1)
print("after adding the elements")
l1.append(50)
print(l1)
print("after  pop the element")
l1.pop()
print(l1)
print("inserting the elements")
l1.insert(4,50)
print(l1)
print("after removeing the elements")
l1.remove(50)
print(l1)