color=["red","yellow","green","black"]
print(type(color))
color=("red","yellow","green","black")
print(type(color))
color={"red","yellow","green","black"}
print(type(color))
color_d={
    1:"red",
    2:"yellow",
    3:"green",
    4:"black"
    }
print(type(color_d))
print(color_d)