CREATE TABLE EMPLOYEE(
EID INTEGER,
ENAME VARCHAR(32),
ESAL FLOAT,
LOCATION VARCHAR(32));

VARCHAR DEFULT SIZE IS 256

INSERT INTO EMPLOYEE VALUES(101,'Dhanush',55000.45,'BANGALORE');

UPDATE EMPLOYEE SET LOCATION='NEW DELHI' WHERE LOCATION='NEW DEHIL';


CREATE TABLE products(
pid  INTEGER,
pname VARCHAR(32),
price  INTEGER,
category VARCHAR(32));

INSERT INTO products VALUES(10,'SAMSUNG GALAXY',25000,'MOBILE');
INSERT INTO products VALUES(11,'VIVO',35000,'MOBILE');
INSERT INTO products VALUES(12,'MARKER PEN',30,'ARTICle');
INSERT INTO products(pid,pname) VALUES(13,'LAPTOP','ELECTORNIC GADGETS');

MYSQL CONSTRAINTS

NOT NULL= NULL VALUES NOT ALLOWED BUT DUPLICATES ARE ALLOWED

UNIQUE=DUPLICATES ARE NOT ALLOWED  BUT NULL VALUES ARE ALLOWED

CHECK= CHECKING THE CONDITION

DEFAULT= DEFAULT VALUE

PRIMARY KEY=NOTNULL +UNIQUE KEY

FOREIGN KEY=REFERENCES INTEGRITY

INDEX=
